apiVersion: v1
kind: Service
metadata:
  name: my-diary-app-service
spec:
  type: NodePort
  selector:
    app: mydiary-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000 # Specify the node port here, ensure it's within your cluster's allowed range
