apiVersion: v1
kind: Secret
metadata:
  name: session-secret
type: Opaque
data:
  SESSION_SECRET: "NWFmNzU3N2M4YWI3NzEwNTgxZTYzNzliYmM4N2JmZGZlNDA4MDViNzJkZDMzNzY4NDgzMGQ4ZWFiMWE1Y2Q2MDgzNmM0NjAxMjI0NmQ2MGM5ZmZkZTJhNjc3OGUyY2RjZDc0MzhkZTE0YzM4NmE1MTlhN2ViNmU2NGM5ZTgzZTU="
