apiVersion: apps/v1
kind: Deployment
metadata:
  name: diarydb-sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diarydb-sqlserver
  template:
    metadata:
      labels:
        app: diarydb-sqlserver
    spec:
      containers:
        - name: diarydb-sqlserver
          image: himashveta/diarydb-sqlserver:latest
          ports:
            - containerPort: 1433
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: DiaryDB
