apiVersion: apps/v1
kind: Deployment
metadata:
  name: diary-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diary
  template:
    metadata:
      labels:
        app: diary
    spec:
      containers:
      - name: diary
        image: cb946801/diary-app:latest  
        ports:
        - containerPort: 8000
