apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-nginx
  template:
    metadata:
      labels:
        app: django-nginx
    spec:
     containers:
      - name: django-nginx
        image: your-django-nginx-image:v1  # Replace with your Docker image
        ports:
        - containerPort: 80
    
        - name: django
          image: as937801/django:latest  # Replace with your Docker image
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "django.settings"
            # Add other environment variables for database, etc.
