apiVersion: apps/v1
kind: Deployment
metadata:
  name: diary-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diary
  template:
    metadata:
      labels:
        app: diary
    spec:
      containers:
      - name: diary-site
        image: cb946801/diary-site:v1
        ports:
        - containerPort: 80
